# Site settings
title: Navid Kazempour
email: n.kazempour@gmail.com
url: https://example.github.io
# description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
# footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/n_kazempour
  - title: facebook
    url: https://www.facebook.com/n.kazempour
  - title: google-plus
    url: https://plus.google.com/u/0/115500194478905836003/posts
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  - title: linkedin
    url: https://ca.linkedin.com/in/navid-kazempour-88906795
  - title: github
    url: https://github.com/navidkazempour

# Build settings
markdown: kramdown
permalink: pretty
